### ISSUE TITLE
Comments on "eck-on-gke" 2020-Apr-1

### ISSUE THREAD

**Issue by MorrieAtElastic** [immavalls/eck-on-gke#1]
(1) if any operations fail because of permissions issues for example: 

`Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "morris.schreibman@elastic.co" cannot create resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope:
Required "container.clusterRoleBindings.create" permission.`

the most probable cause is that your GCP account does not have cluster-admin privilege. You should be able to assign this privilege to your GCP account yourself. See https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#iam-rolebinding-bootstrap. 

(2) My attempts to create an elastic cluster initially failed using the various cluster defaults. I found that is I specified my cluster nodes as "e2-standard-2" with  2 CPUs and  8GBytes per node I was able to successfully create my cluster.

**Comment by immavalls** [comment]
Better documentation on how to create a GKE cluster with 4 cores and 16Gb each worker https://github.com/immavalls/eck-on-gke/blob/master/install-gke-and-eck.md#create-a-gke-cluster
